#!/usr/bin/env python3
"""Build script for ViTaiViewer - auto-detects Windows/Linux."""

import os
import sys
import platform
import subprocess
from pathlib import Path


# 项目根目录，即 build.py 所在目录
PROJECT_ROOT = Path(__file__).resolve().parent

# 构建信息输出文件
BUILD_INFO_FILE = PROJECT_ROOT / "app" / "build_info.py"


def get_git_branch():
    """
    获取当前项目的 Git 分支。

    正常分支:
        dev/1.0.1

    detached HEAD:
        回退为短 commit SHA，例如 a1b2c3d

    Git 不可用或执行失败:
        unknown
    """
    try:
        branch = subprocess.check_output(
            ["git", "branch", "--show-current"],
            cwd=PROJECT_ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()

        if branch:
            return branch

        # detached HEAD 状态，尝试使用短 commit SHA
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()

        return commit or "unknown"

    except (
        subprocess.CalledProcessError,
        FileNotFoundError,
        OSError,
    ):
        return "unknown"


def get_wheel_path():
    """
    Return the appropriate pyvitaisdk wheel for the current platform.

    如果目录中存在多个 wheel，选择最近修改的一个。
    """
    if sys.platform == "win32":
        wheel_dir = PROJECT_ROOT / "wheels" / "windows"
    else:
        wheel_dir = PROJECT_ROOT / "wheels" / "linux"

    if not wheel_dir.is_dir():
        raise FileNotFoundError(
            f"Wheel directory not found: {wheel_dir}"
        )

    wheels = [
        path
        for path in wheel_dir.iterdir()
        if path.is_file() and path.suffix == ".whl"
    ]

    if not wheels:
        raise FileNotFoundError(
            f"No .whl found in {wheel_dir}"
        )

    # 保证当目录中存在多个 wheel 时选择规则稳定且明确：
    # 使用最近修改的 wheel。
    wheel = max(
        wheels,
        key=lambda path: path.stat().st_mtime,
    )

    if len(wheels) > 1:
        print(
            f"WARNING: Multiple wheels found in {wheel_dir}."
        )
        print(
            f"         Using most recently modified wheel: {wheel.name}"
        )

    return wheel


def write_build_info(wheel_path):
    """
    将 Git 分支和实际使用的 SDK wheel 信息写入 app/build_info.py。

    main_window.py 运行时只读取该模块，
    不需要执行 Git 命令，也不需要重新扫描 wheel。
    """
    git_branch = get_git_branch()

    # 例如：
    # pyvitaisdk4bc-1.0.13-py3-none-win_amd64.whl
    #
    # 转换为：
    # pyvitaisdk4bc-1.0.13-py3-none-win_amd64
    sdk_wheel = wheel_path.stem

    content = f'''"""Auto-generated build information.

This file is generated by build.py.
Do not edit GIT_BRANCH or SDK_WHEEL manually.
"""

GIT_BRANCH = {git_branch!r}
SDK_WHEEL = {sdk_wheel!r}


def get_build_info() -> str:
    """Return build information suitable for UI display."""
    return f"Git: {{GIT_BRANCH}} | SDK: {{SDK_WHEEL}}"


def get_window_title(
    base_title: str = "ViTai 视触觉传感器查看器",
) -> str:
    """Return the application window title with build information."""
    return f"{{base_title}} | {{get_build_info()}}"
'''

    BUILD_INFO_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    BUILD_INFO_FILE.write_text(
        content,
        encoding="utf-8",
    )

    print("[Build Info]")
    print(f"      Git branch: {git_branch}")
    print(f"      SDK wheel : {sdk_wheel}")
    print(f"      Output    : {BUILD_INFO_FILE}")


def install_sdk(wheel):
    """Install pyvitaisdk from the selected platform-specific wheel."""
    print(
        f"[1/4] Installing pyvitaisdk from: {wheel.name}"
    )

    ret = os.system(
        f'"{sys.executable}" -m pip install "{wheel}"'
    )

    if ret != 0:
        print(
            "WARNING: pyvitaisdk install failed. "
            "Ensure the wheel is present."
        )
    else:
        print("       OK")


def install_deps():
    """Install cross-platform Python dependencies."""
    print("[2/4] Installing dependencies...")

    ret = os.system(
        f'"{sys.executable}" -m pip install '
        "PyQt6 pyqtgraph opencv-python numpy"
    )

    if ret != 0:
        raise RuntimeError(
            "Failed to install dependencies."
        )


def build_exe():
    """Build the single-file executable with PyInstaller."""
    sep = ";" if sys.platform == "win32" else ":"
    name = "ViTaiViewer"

    cmd = (
        f'pyinstaller --onefile --windowed --name "{name}" '
        f'--add-data "app{sep}app" '
        f"--collect-all pyvitaisdk "
        f"--collect-submodules scipy "
        f"--collect-submodules skimage "
        f"--collect-submodules cryptography "
        f"--collect-submodules appdirs "
        f"--collect-all comtypes "
        f"--hidden-import PyQt6 "
        f"--hidden-import pyqtgraph "
        f"--hidden-import cv2 "
        f"--hidden-import colorlog "
        f"--hidden-import coloredlogs "
        f"--hidden-import onnxruntime "
        f"--hidden-import matplotlib "
        f"--hidden-import appdirs "
        f"main.py"
    )

    print(f"[3/4] Building {name}...")
    print(
        f"      Platform: "
        f"{platform.system()} {platform.machine()}"
    )
    print(
        f"      Python: {platform.python_version()}"
    )

    ret = os.system(cmd)

    if ret != 0:
        raise RuntimeError("Build failed.")


def main():
    print("=" * 50)
    print("  ViTai Sensor Viewer - Build Script")
    print(
        f"  Platform: "
        f"{platform.system()} {platform.machine()}"
    )
    print("=" * 50)
    print()

    # ---------------------------------------------------------
    # 1. 确定本次真正使用的 SDK wheel
    # ---------------------------------------------------------
    wheel = get_wheel_path()

    # ---------------------------------------------------------
    # 2. 在任何正式构建动作之前生成构建信息
    #
    # app/build_info.py 中将写入：
    #
    # GIT_BRANCH = "dev/1.0.1"
    # SDK_WHEEL = "pyvitaisdk4bc-1.0.13-py3-none-win_amd64"
    # ---------------------------------------------------------
    write_build_info(wheel)

    print()

    # ---------------------------------------------------------
    # 3. 安装与 build_info.py 中完全相同的 wheel
    # ---------------------------------------------------------
    install_sdk(wheel)

    print()

    install_deps()

    print()

    build_exe()

    dist = PROJECT_ROOT / "dist"

    print()
    print("[4/4] Build complete!")

    exe_name = (
        "ViTaiViewer.exe"
        if sys.platform == "win32"
        else "ViTaiViewer"
    )

    print(f"      Output: {dist / exe_name}")


if __name__ == "__main__":
    main()